version: "3.9"
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ezyapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  flyway:
    image: flyway/flyway:9
    command: -url=jdbc:postgresql://postgres:5432/ezyapp -schemas=public -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - postgres
volumes:
  postgres:
    driver: local
